exports.ids = [
	{"id":0,"Savivaldybė":"Akmenės r. sav."},
	{"id":1,"Savivaldybė":"Alytaus m. sav."},
	{"id":2,"Savivaldybė":"Alytaus r. sav."},
	{"id":3,"Savivaldybė":"Anykščių r. sav."},
	{"id":4,"Savivaldybė":"Birštono sav."},
	{"id":5,"Savivaldybė":"Biržų r. sav."},
	{"id":6,"Savivaldybė":"Druskininkų sav."},
	{"id":7,"Savivaldybė":"Elektrėnų sav."},
	{"id":8,"Savivaldybė":"Ignalinos r. sav."},
	{"id":9,"Savivaldybė":"Jonavos r. sav."},
	{"id":10,"Savivaldybė":"Joniškio r. sav."},
	{"id":11,"Savivaldybė":"Jurbarko r. sav."},
	{"id":12,"Savivaldybė":"Kaišiadorių r. sav."},
	{"id":13,"Savivaldybė":"Kalvarijos sav."},
	{"id":14,"Savivaldybė":"Kauno m. sav."},
	{"id":15,"Savivaldybė":"Kauno r. sav."},
	{"id":16,"Savivaldybė":"Kazlų Rūdos sav."},
	{"id":17,"Savivaldybė":"Kėdainių r. sav."},
	{"id":18,"Savivaldybė":"Kelmės r. sav."},
	{"id":19,"Savivaldybė":"Klaipėdos m. sav."},
	{"id":20,"Savivaldybė":"Klaipėdos r. sav."},
	{"id":21,"Savivaldybė":"Kretingos r. sav."},
	{"id":22,"Savivaldybė":"Kupiškio r. sav."},
	{"id":23,"Savivaldybė":"Lazdijų r. sav."},
	{"id":24,"Savivaldybė":"Marijampolės sav."},
	{"id":25,"Savivaldybė":"Mažeikių r. sav."},
	{"id":26,"Savivaldybė":"Molėtų r. sav."},
	{"id":27,"Savivaldybė":"Neringos sav."},
	{"id":28,"Savivaldybė":"Pagėgių sav."},
	{"id":29,"Savivaldybė":"Pakruojo r. sav."},
	{"id":30,"Savivaldybė":"Palangos m. sav."},
	{"id":31,"Savivaldybė":"Panevėžio m. sav."},
	{"id":32,"Savivaldybė":"Panevėžio r. sav."},
	{"id":33,"Savivaldybė":"Pasvalio r. sav."},
	{"id":34,"Savivaldybė":"Plungės r. sav."},
	{"id":35,"Savivaldybė":"Prienų r. sav."},
	{"id":36,"Savivaldybė":"Radviliškio r. sav."},
	{"id":37,"Savivaldybė":"Raseinių r. sav."},
	{"id":38,"Savivaldybė":"Rietavo r. sav."},
	{"id":39,"Savivaldybė":"Rokiškio r. sav."},
	{"id":40,"Savivaldybė":"Skuodo r. sav."},
	{"id":41,"Savivaldybė":"Šakių r. sav."},
	{"id":42,"Savivaldybė":"Šalčininkų r. sav."},
	{"id":43,"Savivaldybė":"Šiaulių m. sav."},
	{"id":44,"Savivaldybė":"Šiaulių r. sav."},
	{"id":45,"Savivaldybė":"Šilalės r. sav."},
	{"id":46,"Savivaldybė":"Šilutės r. sav."},
	{"id":47,"Savivaldybė":"Širvintų r. sav."},
	{"id":48,"Savivaldybė":"Švenčionių r. sav."},
	{"id":49,"Savivaldybė":"Tauragės r. sav."},
	{"id":50,"Savivaldybė":"Telšių r. sav."},
	{"id":51,"Savivaldybė":"Trakų r. sav."},
	{"id":52,"Savivaldybė":"Ukmergės r. sav."},
	{"id":53,"Savivaldybė":"Utenos r. sav."},
	{"id":54,"Savivaldybė":"Varėnos r. sav."},
	{"id":55,"Savivaldybė":"Vilkaviškio r. sav."},
	{"id":56,"Savivaldybė":"Vilniaus m. sav."},
	{"id":57,"Savivaldybė":"Vilniaus r. sav."},
	{"id":58,"Savivaldybė":"Visagino m. sav."},
	{"id":59,"Savivaldybė":"Zarasų r. sav."}
]